DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tastings;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
username TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,
activated BOOLEAN NOT NULL);

CREATE TABLE tastings (
id SERIAL PRIMARY KEY,
created TIMESTAMP WITH TIME ZONE NOT NULL,
tasting_name TEXT,
created_by TEXT NOT NULL);